[build]
  base = "ocbs-frontend"
  command = "npm install && npm run build"
  publish = "ocbs-frontend/build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "/.netlify/functions/api"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
