[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "18"
  REACT_APP_API_URL = "https://ocbs-backend.windsurf.build/.netlify/functions/api"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
